learning_site/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

# make our variable, a list, in the old Django, it didn't use to be a list, now it's just a list
urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('<int:course_pk>/t<int:step_pk>/', views.text_detail, name='text_detail'),  # 2.3
    path('<int:course_pk>/q<int:step_pk>/', views.quiz_detail, name='quiz_detail'),  # 2.3
    # path('<int:course_pk>/<int:step_pk>/', views.step_detail, name='step_detail'), # 在2.3去掉
    path('<int:course_pk>/create_quiz/', views.quiz_create, name='quiz_create'),
    path('<int:course_pk>/edit_quiz/<int:quiz_pk>/', views.quiz_edit, name='quiz_edit'),
    path('<int:quiz_pk>/create_question/<question_type>/', views.create_question, name='create_question'),
    path('<int:quiz_pk>/edit_question/<int:question_pk>/', views.edit_question, name='edit_question'),
    path('<int:question_pk>/create_answer/', views.answer_form, name='create_answer'),
    path('<int:pk>/', views.course_detail, name='course_detail'),
    path('by/<teacher>', views.courses_by_teacher, name='courses_by_teacher'),  # 8.2.1
    path('search/', views.search, name='search'),   # 8.2.3
]

learning_site/learning_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views

urlpatterns = [
    path('courses/', include('courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('suggest/', views.suggestion_view, name='suggestion'),
    path('', views.hello_world, name='home'),
]

urlpatterns += staticfiles_urlpatterns()


# 8.1.4 要添加这部分加上settings.py中的DEBUG_TOOLBAR_CONFIG内容一起才可以
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

learning_site/courses/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User  # 8.2 引用django自身的User模型


# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)   # 8.1.2给我们的User模型添加一个FK
    subject = models.CharField(default='', max_length=100)        # 8.1.2 保存course的subject是什么
    published = models.BooleanField(default=False)                # 8.2.5

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        abstract = True
        ordering = ['order', ]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):  # 2.3
        return reverse('courses:text_detail', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id})


class Quiz(Step):
    total_questions = models.IntegerField(default=4)
    times_taken = models.IntegerField(default=0, editable=False)   # 8.3.1， editable=False表示不会在admin中显示

    class Meta:
        verbose_name_plural = 'Quizzes'

    def get_absolute_url(self):  # 2.3
        return reverse('courses:quiz_detail', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id})


# 2.5
class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)  # quiz属性是外键,主键是Question的id/pk
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order', ]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt


class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order', ]

    def __str__(self):
        return self.text

learning_site/courses/forms.py
from django import forms
from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions', ]


# 4.6 创建自定义form media
class QuestionForm(forms.ModelForm):
    class Media:
        css = {'all': ('courses/css/order.css',)}
        js = (
            'courses/js/vendor/jquery.fn.sortable.min.js',
            'courses/js/order.js'
        )


class TrueFalseQuestionForm(QuestionForm):  # 4.6 改成QuestionForm
    class Meta:
        model = models.TrueFalseQuestion
        fields = ['order', 'prompt']


class MultipleChoiceQuestionForm(QuestionForm):  # 4.6 改成QuestionForm
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = ['order', 'prompt', 'shuffle_answers']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ['order', 'text', 'correct']


# 4.1
AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm,
    extra=2,  # 在原有的答案基础上再添加两个可填的答案
    # max_count=4,/min_count=4 还可以添加最大/最小数量, 可以控制forms的数量
)

AnswerInlineFormSet = forms.inlineformset_factory(
    models.Question,   # inline将会在这个模型中出现,,用于保存的模型
    models.Answer,     # 在form中中编辑的模型
    extra=2,
    fields=('order', 'text', 'correct'),
    formset=AnswerFormSet,
    min_num=1,
)

learning_site/courses/views.py
from django.db.models import Q, Count, Sum
from django.shortcuts import render, get_object_or_404
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404

from . import forms

# Create your views here.
# from .models import Course, Step
from . import models


def course_list(request):
    # courses = Course.objects.all()
    # output = ','.join(courses)
    # output = ", ".join([str(course) for course in courses])
    # courses = models.Course.objects.all()
    # email = 'questions@learning_site.com'
    # return render(request, 'courses/course_list.html', {'courses': courses, 'email': email})

    # courses = models.Course.objects.filter(published=True)   # 8.2.5 显示published的courses列表
    # 8.3.5-1
    courses = models.Course.objects.filter(published=True).annotate(
        total_steps=Count('text', distinct=True) + Count('quiz', distinct=True))
    # 8.3.5-3, total前者是字典的名字,后者是一个参数
    total_sum = courses.aggregate(total=Sum('total_steps'))
    return render(request, 'courses/course_list.html', {'courses': courses,
                                                        'total_sum': total_sum})


def course_detail(request, pk):
    # # course = Course.objects.get(pk=pk)
    # course = get_object_or_404(models.Course, pk=pk, published=True)  # 8.2.5,添加published的参数
    # steps = sorted(chain(course.text_set.all(), course.quiz_set.all()), key=lambda step: step.order)

    # 8.3.8-1 (try--else), 8.3.8-3 try中添加‘quiz_set__question_set'
    try:
        course = models.Course.objects.prefetch_related('quiz_set', 'text_set', 'quiz_set__question_set').get(pk=pk, published=True)
    except models.Course.DoesNotExist:
        raise Http404
    else:
        steps = sorted(chain(course.text_set.all(), course.quiz_set.all()), key=lambda step: step.order)

    return render(request, 'courses/course_detail.html',
                  {'course': course,
                   'steps': steps})


# 2.3 def step_detail(request, course_pk, step_pk):
def text_detail(request, course_pk, step_pk):
    # step = get_object_or_404(models.Step, course_id=course_pk, pk=step_pk)
    step = get_object_or_404(models.Text, 
                             course_id=course_pk,
                             pk=step_pk,
                             course__published=True)  # 8.2.5,添加published的参数
    return render(request, 'courses/text_detail.html', {'step': step})


# 2.3
def quiz_detail(request, course_pk, step_pk):
    # step = get_object_or_404(models.Quiz,
    #                          course_id=course_pk,
    #                          pk=step_pk,
    #                          course__published=True)  # 8.2.5,添加published的参数
    # return render(request, 'courses/quiz_detail.html', {'step': step})

    # 8.3.8-4, 用select_related()方法，检查属于Step模型中的‘course’字段，Quiz(Step)-->course(Step的外键)
    # 8.3.8-5 在添加一个prefetch_related()
    try:
        step = models.Quiz.objects.select_related('course').prefetch_related(
            'question_set',
            'question_set__answer_set',
        ).get(course_id=course_pk, pk=step_pk, course__published=True)
    except models.Quiz.DoesNotExist:
        raise Http404
    else:
        return render(request, 'courses/quiz_detail.html', {'step': step})


# 处理quizzes的视图--添加一个quiz
@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk, course__published=True)  # 8.2.5,添加published的参数
    form = forms.QuizForm()

    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Quiz added!')
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form, 'course': course})


# 处理quizzes的视图--编辑一个quiz
@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz,
                             pk=quiz_pk,
                             course_id=course_pk,
                             course__published=True)  # 8.2.5,添加published的参数
    form = forms.QuizForm(instance=quiz)    # 实例化
    # 处理点击保存键后不会跳转到到同一页面,而是真的将编辑好的内容保存的操作
    # POST是提交request
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Update {}'.format(form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {'form': form, 'course': quiz.course})


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':                       # 这里我们要知道应该用哪一种form
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm

    form = form_class()
    answer_forms = forms.AnswerInlineFormSet(
        queryset=models.Answer.objects.none()   # 4.4因为我们是创建一个question,这个question没有答案,要一个空的queryset
    )

    if request.method == 'POST':         # 这个部分跟我们在创建quizzes的视图中做得是一样的
        form = form_class(request.POST)  # 如果上面实例化了, 这里就不能这样做了
        answer_forms = forms.AnswerInlineFormSet(  # 4.4
            request.POST,
            queryset=models.Answer.objects.none()
        )
        if form.is_valid() and answer_forms.is_valid():  # 4.4 answer_forms也是valid的话
            # if form.is_valid():
            question = form.save(commit=False)           # 创建一个问题
            question.quiz = quiz
            question.save()
            answers = answer_forms.save(commit=False)    # 4.4
            for answer in answers:                       # 4.4
                answer.question = question               # 4.4
                answer.save()                            # 4.4
            messages.success(request, 'Added question')
            return HttpResponseRedirect(quiz.get_absolute_url())

    return render(request, 'courses/question_form.html', {'quiz': quiz,
                                                          'form': form,
                                                          'formset': answer_forms})


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
        question = question.truefalsequestion               #这个确保编辑问题是保存了shuffle answer这个选项
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)
    answer_forms = forms.AnswerInlineFormSet(  # 4.4
        queryset=form.instance.answer_set.all()
    )

    # 保存
    if request.method == 'POST':
        form = form_class(request.POST, instance=question)
        answer_forms = forms.AnswerInlineFormSet(    # 4.4
            request.POST,
            queryset=form.instance.answer_set.all()
        )
        if form.is_valid() and answer_forms.is_valid():    # 4.4 answer_forms也是valid的
            form.save()
            answers = answer_forms.save(commit=False)      # 4.4
            for answer in answers:                         # 4.4
                answer.question = question                 # 4.4
                answer.save()                              # 4.4
            for answer in answer_forms.deleted_objects:    # 4.6
                answer.delete()
            messages.success(request, 'Updated question')
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {
        'form': form,
        'quiz': question.quiz,
        'formset': answer_forms})                          # 4.4


@login_required
def answer_form(request, question_pk, answer_pk=None):
    question = get_object_or_404(models.Question, pk=question_pk)
    formset = forms.AnswerFormSet(queryset=question.answer_set.all())

    if request.method == 'POST':
        formset = forms.AnswerFormSet(request.POST, queryset=question.answer_set.all())

        if formset.is_valid():
            answers = formset.save(commit=False)  # from here course_id

            for answer in answers:
                answer.question = question
                answer.save()                    # to here,  =  formset.save()

            messages.success(request, 'added answers')
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/answer_form.html', {'question': question, 'formset': formset})


def courses_by_teacher(request, teacher):  # 8.2.1
    # teacher = models.User.objects.get(username=teacher)
    # courses = teacher.course_set.all()
    courses = models.Course.objects.filter(teacher__username=teacher,   # 这个双下划线是从一个模型到另一个模型，teacher是要给外键
                                           published=True)  # 8.2.5
    return render(request, 'courses/course_list.html', {'courses': courses})


def search(request):            # 8.2.3
    term = request.GET.get('q')
    # courses = models.Course.objects.filter(
    #     title__icontains=term,  # 这个双下划线是选择该模型得一个字段
    #     description__icontains=term,   # 我们可以这样添加另一个filter，但是这实际上时创建一个’AND‘条件
    #     published=True)  # 8.2.5

    # courses = models.Course.objects.filter(
    #     title__icontains=term,  # 这个双下划线是选择该模型得一个字段
    #     published=True
    # ).filter(description__icontains=term)    # 8.3.3 先完成第一个filter，再做第二个filter

    # # 8.3.3
    # courses = models.Course.objects.filter(
    #     published=True
    # ).filter(
    #     Q(title__icontains=term) | Q(description__icontains=term)
    # )
    
    # 改良

learning_site/courses/templates/courses/course_detail.html
{#{% extends "layout.html" %}#}
{#{% load humanize course_extras %}#}
{#<!--{% load course_extras %}-->#}
{##}
{#{% block title %}{{ course.title }}{% endblock %}#}
{##}
{#{% block content %}#}
{#<article>#}
{#    <h2>{{ course.title }}</h2>#}
{#<!--    {{ course.description|markdown_to_html|safe }}-->#}
{#    {{ course.description|markdown_to_html }}#}
{##}
{#    <!--    <p>These are the step(s) in this course: {{ course.step_set.all|join:", " }}</p>-->#}
{#<!--    <p>There are {{ course.step_set.all|length }} step(s) in this course: {{ course.step_set.all|join:", " }}</p>-->#}
{#<!--        <p>There are {{ course.step_set.count }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>-->#}
{#        <p>There are {{ course.step_set.count|apnumber }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>#}
{#    #}
{#    <section>#}
{#        {% for step in course.step_set.all %}#}
{#            <h3>#}
{#                <a href="{% url 'courses:step_detail' course_pk=course.pk step_pk=step.pk %}">{{ step.title }}</a>#}
{#            </h3>#}
{#            {{ step.description}}#}
{#        {% endfor %}#}
{#    </section>#}
{#</article>#}
{#{% if user.is_authenticated %}#}
{#<hr>#}
{#<a href="{% url 'courses:quiz_create' course_pk=course.id %}" class="button">New Quiz</a>#}
{#{% endif %}#}
{#{% endblock %}#}

{#--Django Forms-------------------------------------------------------------------------------------------#}
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}</h1>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl>
                {# 2.3#}
                {% for step in steps %}
                    <dt>
                        <a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    </dt>
                    <dd>{{ step.description|markdown_to_html }}</dd>
                    
                    {#-----------8.3.8-2 --计算一个quiz有多少个question-----------#}
                    {% if step.question_set.all %}
                        <dt>Total quesitons</dt>
                        <dd>{{ step.question_set.count }}</dd>
                    {%  endif %}
                {% endfor %}
            </dl>
        </article>
        {% if user.is_authenticated %}
            <hr>
            <a href="{% url 'courses:quiz_create' course_pk=course.id %}" class="button">New Quiz</a>
        {% endif %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/question_form.html
{% extends 'courses/layout.html' %}
{% load course_extras %}


{#{% block title %}New Question for {{ quiz.title }} | {{ quiz.course.title }} {{ block.super }}{% endblock %}#}
{#{% block title %}{{ form.instance.prompt|default:"New Question" }} | {{ quiz.course.title }} {{ block.super}}{% endblock %}#}
{##}
{#{% block breadcrumbs %}#}
{#    <li><a href="{% url 'courses:course_detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>#}
{#    <li><a href="{% url 'courses:quiz_detail' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#<div class="row columns">#}
{#    {{ block.super }}#}
{#<!--        <h1>Make a new question</h1>-->#}
{#    <h1>{{ form.instance.prompt|default:"Make a new question" }}</h1>#}
{#    <form method="POST" action="">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        #}
{#        {{ formset.management_form }}#}
{#        #}
{#        <table role="grid" class="stack hover" style="width: 100%">#}
{#            <thead>#}
{#                <tr>#}
{#                    <th scope="col" class="text-center" style="width: 10%">Order</th>#}
{#                    <th scope="col" class="text-center">Center</th>#}
{#                    <th scope="col" class="text-center" style="width: 10%">Correct</th>#}
{#                    <th scope="col" class="text-center" style="width: 10%">Delete</th>#}
{#                </tr>#}
{#            </thead>#}
{#            <tbody class="order">#}
{#                {% for form in formest %}#}
{#                    <tr class="answer-form {% if form.instance.pk %}item{% else %}new{% endif %}">#}
{#                        <td>{{ form.id }}{{ form.order }}</td>#}
{#                        <td>{{ form.text }}</td>#}
{#                        <td class="text-center">{{ form.correct }}</td>#}
{#                        {% if form.instance.pk %}#}
{#                            <td class="text-center">{{ form.DELETE }}</td>#}
{#                        {% else %}#}
{#                            <td class="text-center"></td>#}
{#                        {% endif %}#}
{#                    </tr>#}
{#                    #}
{#                {% endfor %}#}
{#            </tbody>#}
{#        </table>#}
{#        #}
{#        #}
{#        <input type="submit" class="button" value="Save">#}
{#    </form>#}
{#        {% if user.is_authenticated and form.instance.pk %}#}
{#            <hr>#}
{#<!--            <a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}}" class="button">Add Answer</a>-->#}
{#            <a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}}" class="button">Answers</a>#}
{##}
{#        {% endif %}#}
{#</div>#}
{#{% endblock %}#}
{##}
{# 4.6 #}
{#{% block css %}#}
{#    {{ form.media.css }}#}
{#{% endblock %}#}
{##}
{#{% block javascript %}#}
{#    {% load static %}#}
{#    {{ form.media.js }}#}
{#    <script src="{% static 'js/vendor/jquery.formset.js' %}"></script>#}
{#    <script>#}
{#        $('.answer-form').formset({#}
{#            addText: 'add answer',#}
{#            deleteText: 'remove'#}
{#        });#}
{#    </script>#}
{#{% endblock %}#}


{#{% block title %}New Question for {{ quiz.title }} | {{ quiz.course.title }} {{ block.super}}{% endblock %}#}
{% block title %}{{ form.instance.prompt|default:"New Question" }} | {{ quiz.course.title }} {{ block.super}}{% endblock %}


{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz_detail' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super}}
{#        <h1>Make a new question</h1>#}
        <h1>{{ form.instance.prompt|default:'Make a new question' }}</h1>
        <form method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            
            {{ formset.management_form }}
            
            <table role="grid" class="stack hover" style="width: 100%">
                <thead>
                    <tr>
                        <th scope="col" class="text-center" style="width: 10%">Order</th>
                        <th scope="col" class="text-center">Text</th>
                        <th scope="col" class="text-center" style="width: 10%">Correct</th>
                        <th scope="col" class="text-center" style="width: 10%">Delete?</th>
                    </tr>
                </thead>
                <tbody class="order">
                    {% for form in formset %}
                        <tr class="answer-form {%  if form.instance.pk %}item{% else %}new{% endif %}">
                            <td>{{ form.id }}{{ form.order }}</td>
                            <td>{{ form.text }}</td>
                            <td class="text-center">{{ form.correct }}</td>
                            {% if form.instance.pk %}
                                <td class="text-center">{{ form.DELETE }}</td>
                            {% else %}
                                <td class="text-center"></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            
            <input type="submit" class="button" value="Save">
        </form>
{#        {% if user.is_authenticated and form.instance.pk %}#}
{#            <hr>#}
            {#<a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}" class="button">And Answer</a>#}
            {#4.1#}
{#            <a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}" class="button">Answers</a>   #}
{##}
{#        {% endif %}#}
    </div>
{% endblock %}

{% block css %}
    {{ form.media.css }}
{% endblock %}

{% block javascript %}
    {% load static %}
    {{ form.media.js }}
    <script src="{% static 'js/vendor/jquery.formset.js' %}"></script>
    <script>
        $('.answer-form').formset({
            addText: 'add answer',
            deleteText: 'remove'
        });
    </script>
{% endblock %}

learning_site/courses/templates/courses/quiz_detail.html
{#{% extends 'courses/layout.html' %}#}
{#{% load course_extras %}#}
{##}
{#{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}#}
{##}
{#{% block breadcrumbs %}#}
{#    <li><a href="{% url 'courses:step_detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#    <div class="row columns">#}
{#        <article>#}
{#            {{ block.super }}#}
{#            <h1>{{ step.title }}</h1>#}
{#            <ul class="no-bullet">#}
{#                {% for question in step.question_set.all %}#}
{#                <li>#}
{#                    <h2>{{ question.prompt }}</h2>#}
{#                    {% for answer in question.answer_set.all %}#}
{#                        <div class="callout">{{ answer.text }}</div>#}
{#                    {% endfor %} #}
{#                    {% if user.is_authenticated %}#}
{#                        <a href="{% url 'courses:edit_question}' question_pk=question.pk quiz_pk=step.pk %}">Edit</a>#}
{#                    {% endif %}#}
{#                </li>#}
{#                {% endfor %}#}
{#            </ul>#}
{#            {% for question in step.question_set.all %}#}
{#                <p>{{ question.prompt }}</p>#}
{#            {% endfor %}#}
{#        </article>#}
{#        {% if user.is_authenticated %}#}
{#        <hr>#}
{#        <a href="{% url 'courses:quiz_edit' course_pk=step.course.pk quiz_pk=step.pk %}" class="button">Edit</a>#}
{#        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc' %}" class="button">New Multiple Choice Question</a>#}
{#        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf' %}" class="button">New True/False Question</a>#}
{#        {% endif %}#}
{#    </div>#}
{#{% endblock %}#}


{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:course_detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
                {% for question in step.question_set.all %}
                    <li>
                        <h2>{{ question.prompt }}</h2>
                        {% for answer in question.answer_set.all %}
                            <div class="callout">{{ answer.text }}</div>
                        {% endfor %}
                        {% if user.is_authenticated %}
                            <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="button">Edit</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </article>
        {% if user.is_authenticated %}
            <hr>
            <a href="{% url 'courses:quiz_edit' course_pk=step.course.pk quiz_pk=step.pk %}" class="button">Edit</a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="mc" %}" class="button">New Multiple Choice</a>
            <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type="tf" %}" class="button">New True/False</a>
        {% endif %}
    </div>
{% endblock %}